name: build-airmap

on: [push, pull_request]

jobs:

  build-android-ndk-r21-api-level-33:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Ubuntu environment
        run: |
          sudo tools/ubuntu/setup.dev.sh
          sudo apt-get install -y qt5-default qtbase5-dev
          echo "Qt5_DIR=/usr/lib/x86_64-linux-gnu/cmake/Qt5" >> $GITHUB_ENV
             
      - name: Update git submodules
        run: |
          git submodule sync
          git submodule update --init --recursive
      - name: Build and test
        run: |
          ndk=$(tools/android/download-ndk.sh android-ndk-r21d /tmp)
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-30 -DANDROID_STL=c++_shared -DANDROID_CPP_FEATURES="rtti exceptions" -DCMAKE_TOOLCHAIN_FILE=${ndk}/build/cmake/android.toolchain.cmake -DCMAKE_EXE_LINKER_FLAGS="-llog" -DQt5_DIR="/usr/lib/x86_64-linux-gnu/cmake/Qt5" ..
          make -j4
          ctest -V
          sudo make install
      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-ndk-r21-api-level-33-artifacts
          path: build
